begin SENSOR_GLOBAL
end SENSOR_GLOBAL

begin SENSOR_UNIT_1
    type = external_sensor
    name = cabin_aq
    address = /data/var/tmp/aq/libaq_external_sensor.so
    data_format = SENSOR_FORMAT_USER_DATA
    frequency = 1
    bus = sim
    sim_pollute = 1
end SENSOR_UNIT_1
